FROM  ubuntu:14.04

RUN apt-get update && apt-get install -y puppet

COPY puppet /tmp/puppet

WORKDIR /tmp/puppet

RUN puppet apply /tmp/puppet/tomcat7.pp

RUN chmod +x /tmp/puppet/tomcat_start.sh

ENTRYPOINT [ "/tmp/puppet/tomcat_start.sh"]
