# -*- mode: ruby -*-
# vi: set ft=ruby :

# Author: S. Guclu
# description: created VM and provisions basic tools for continuous deployment chain

Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |d|
    d.image="ubuntu:14.04"
    d.remains_running=true
    d.cmd=["/bin/bash"]
  end
  
  config.vm.provision :puppet do |puppet|
     #puppet.options = "--debug"
     puppet.manifests_path = "puppet"
     puppet.manifest_file = "tomcat7.pp"
  end
  
end
